dist: xenial
sudo: required
language: cpp
compiler: gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          update: true
          packages:
            - g++-7
            - libgl1-mesa-dev
            - pkg-config
            - libsdl2-dev
            - libopenal-dev
            - libalut-dev
            - libvorbis-dev
            - liblua5.3-dev

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - ./helper.sh -b
